# Site Settings
title: Distributed Systems Practice | A Blog About Learning Dist Sys
email: pat_cody@gwu.edu
description: A blog about my work learning topics in CSCI 6421, Distributed Systems.
baseurl: "/dist-sys-practice" # the subpath of your site, e.g. /blog
url: "http://patcody.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: pcodes
user_description: A junior CS student at GWU.

# Social Media
# Remove the item if you don't need it
github_username: pcodes

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
